// src/utils/certificateGenerator.ts
// Phase 3 — Certificate PDF generation using pdfkit
// Install: npm install pdfkit @types/pdfkit

import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';
import { formatDate } from './dateUtils';

export interface CertificateData {
  studentName: string;
  eventTitle: string;
  eventDate: Date;
  clubName: string;
  pointsAwarded: number;
  hoursAwarded: number;
  multiplier: number;
  tier: string;
}

/**
 * Generates a certificate PDF and returns a Buffer.
 * The buffer is suitable for attaching to an email or uploading to Cloudinary.
 */
export async function generateCertificatePDF(data: CertificateData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: 60 });
    const stream = new PassThrough();
    const chunks: Buffer[] = [];

    stream.on('data', (chunk: Buffer) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);

    doc.pipe(stream);

    // ── Background & Border ──────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, doc.page.height).fill('#0f172a');
    doc
      .rect(20, 20, doc.page.width - 40, doc.page.height - 40)
      .lineWidth(3)
      .strokeColor('#6366f1')
      .stroke();

    // ── Header ───────────────────────────────────────────────────────────────
    doc
      .fillColor('#6366f1')
      .fontSize(13)
      .font('Helvetica-Bold')
      .text('CLUBHUB', 0, 50, { align: 'center', characterSpacing: 6 });

    doc
      .fillColor('#ffffff')
      .fontSize(32)
      .font('Helvetica-Bold')
      .text('Certificate of Participation', 0, 78, { align: 'center' });

    // ── Divider ──────────────────────────────────────────────────────────────
    const midY = 130;
    doc.moveTo(80, midY).lineTo(doc.page.width - 80, midY).lineWidth(1).strokeColor('#6366f1').stroke();

    // ── Body ─────────────────────────────────────────────────────────────────
    doc
      .fillColor('#94a3b8')
      .fontSize(13)
      .font('Helvetica')
      .text('This is to certify that', 0, 155, { align: 'center' });

    doc
      .fillColor('#ffffff')
      .fontSize(26)
      .font('Helvetica-Bold')
      .text(data.studentName, 0, 178, { align: 'center' });

    doc
      .fillColor('#94a3b8')
      .fontSize(13)
      .font('Helvetica')
      .text('has successfully participated in', 0, 215, { align: 'center' });

    doc
      .fillColor('#6366f1')
      .fontSize(20)
      .font('Helvetica-Bold')
      .text(`"${data.eventTitle}"`, 0, 238, { align: 'center' });

    doc
      .fillColor('#94a3b8')
      .fontSize(13)
      .font('Helvetica')
      .text(
        `organised by ${data.clubName}  ·  ${formatDate(data.eventDate)}`,
        0,
        268,
        { align: 'center' }
      );

    // ── Stats Row ─────────────────────────────────────────────────────────────
    const statsY = 310;
    const col = doc.page.width / 3;

    _statBox(doc, col * 0 + 40, statsY, `${data.pointsAwarded.toFixed(1)}`, 'AICTE Points');
    _statBox(doc, col * 1 + 40, statsY, `${data.hoursAwarded.toFixed(1)}h`, 'Volunteer Hours');
    _statBox(doc, col * 2 + 40, statsY, `${data.multiplier}×  (${_tierLabel(data.tier)})`, 'Multiplier');

    // ── Footer ────────────────────────────────────────────────────────────────
    doc
      .moveTo(80, doc.page.height - 60)
      .lineTo(doc.page.width - 80, doc.page.height - 60)
      .lineWidth(1)
      .strokeColor('#6366f1')
      .stroke();

    doc
      .fillColor('#475569')
      .fontSize(10)
      .font('Helvetica')
      .text(
        `Generated by ClubHub  ·  ${formatDate(new Date())}`,
        0,
        doc.page.height - 45,
        { align: 'center' }
      );

    doc.end();
  });
}

function _statBox(doc: PDFKit.PDFDocument, x: number, y: number, value: string, label: string) {
  doc
    .fillColor('#ffffff')
    .fontSize(18)
    .font('Helvetica-Bold')
    .text(value, x, y, { width: 180, align: 'center' });

  doc
    .fillColor('#64748b')
    .fontSize(10)
    .font('Helvetica')
    .text(label, x, y + 26, { width: 180, align: 'center' });
}

function _tierLabel(tier: string): string {
  const map: Record<string, string> = {
    non_member: 'Non-Member',
    member: 'Member',
    working_committee: 'Working Committee',
    core: 'Core Member',
  };
  return map[tier] ?? tier;
}
